name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  refresh-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Gmanoori
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake animation"
          branch: main
